"""
Topic bank for daily code project generation.
Each topic is a real, useful mini-project — not filler content.
"""

TOPICS = {
    # === ALGORITHMS ===
    "sorting-visualizer": {
        "category": "Algorithms",
        "title": "Sorting Algorithm Visualizer",
        "description": "Interactive visualization of bubble, merge, quick, and insertion sort with real-time step counting.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["visualizer.py", "algorithms.py", "README.md"],
    },
    "pathfinding-astar": {
        "category": "Algorithms",
        "title": "A* Pathfinding Visualizer",
        "description": "Grid-based A* pathfinding with obstacles, diagonal movement support, and heuristic comparison.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["astar.py", "grid.py", "visualizer.py", "README.md"],
    },
    "bloom-filter": {
        "category": "Data Structures",
        "title": "Bloom Filter Implementation",
        "description": "Probabilistic set membership data structure with configurable false-positive rate and hash functions.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["bloom_filter.py", "test_bloom.py", "README.md"],
    },
    "lru-cache": {
        "category": "Data Structures",
        "title": "LRU Cache from Scratch",
        "description": "Least Recently Used cache using OrderedDict and doubly-linked list, with O(1) get/put operations.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["lru_cache.py", "test_lru.py", "benchmark.py", "README.md"],
    },
    "trie-autocomplete": {
        "category": "Data Structures",
        "title": "Trie-Based Autocomplete Engine",
        "description": "Prefix tree (Trie) implementation with word-frequency ranking for instant search suggestions.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["trie.py", "autocomplete.py", "data.txt", "README.md"],
    },
    "dijkstra-shortest-path": {
        "category": "Algorithms",
        "title": "Dijkstra's Shortest Path on Real Map Data",
        "description": "Find shortest routes on city graph data with priority-queue optimization and path reconstruction.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["dijkstra.py", "graph_loader.py", "cities.json", "README.md"],
    },
    "rate-limiter": {
        "category": "System Design",
        "title": "Rate Limiter — Token Bucket & Sliding Window",
        "description": "Production-grade rate limiter with token bucket, sliding window log, and fixed window counter strategies.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["rate_limiter.py", "strategies.py", "test_rate.py", "README.md"],
    },
    "consistent-hashing": {
        "category": "System Design",
        "title": "Consistent Hashing Ring",
        "description": "Distributed hash ring with virtual nodes, node addition/removal, and rebalancing visualization.",
        "language": "python",
        "difficulty": "advanced",
        "files": ["hash_ring.py", "visualizer.py", "test_hash.py", "README.md"],
    },

    # === UTILITIES ===
    "file-organizer": {
        "category": "Utilities",
        "title": "Smart File Organizer",
        "description": "Automatically categorize and organize messy folders by file type, date, and content patterns.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["organizer.py", "config.yaml", "README.md"],
    },
    "markdown-to-html": {
        "category": "Utilities",
        "title": "Markdown to Static HTML Converter",
        "description": "Convert Markdown files to styled HTML pages with code highlighting, TOC generation, and live preview.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["converter.py", "template.html", "style.css", "README.md"],
    },
    "json-diff-tool": {
        "category": "Utilities",
        "title": "JSON Deep Diff Tool",
        "description": "Compare two JSON files with recursive diff, color-coded output, and patch generation support.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["jsondiff.py", "test_diff.py", "README.md"],
    },
    "env-manager": {
        "category": "Utilities",
        "title": "Environment Variable Manager",
        "description": "CLI tool to manage .env files across projects — encrypt, validate, sync, and template environment variables.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["envman.py", "crypto_utils.py", "README.md"],
    },
    "git-stats": {
        "category": "Utilities",
        "title": "Git Contribution Analyzer",
        "description": "Analyze any git repo for author stats, commit frequency, code churn, and generate HTML reports.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["gitstats.py", "report_template.html", "README.md"],
    },
    "password-generator": {
        "category": "Utilities",
        "title": "Cryptographic Password Generator",
        "description": "Generate memorable passphrases (XKCD-style) and high-entropy passwords with strength estimation.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["passgen.py", "wordlist.txt", "entropy.py", "README.md"],
    },

    # === MINI APPS ===
    "cli-todo": {
        "category": "Mini Apps",
        "title": "Terminal Todo App with SQLite",
        "description": "Full-featured CLI task manager with projects, priorities, due dates, and persistent SQLite storage.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["todo.py", "db.py", "schema.sql", "README.md"],
    },
    "weather-cli": {
        "category": "Mini Apps",
        "title": "Beautiful Terminal Weather App",
        "description": "Fetch weather from OpenWeatherMap API, display with ASCII art icons and 5-day forecast charts.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["weather.py", "icons.py", "README.md"],
    },
    "url-shortener": {
        "category": "Mini Apps",
        "title": "URL Shortener with FastAPI",
        "description": "Self-hosted URL shortener with Base62 encoding, click analytics, custom slugs, and Redis caching.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["main.py", "shorten.py", "models.py", "templates/index.html", "README.md"],
    },
    "pomodoro-timer": {
        "category": "Mini Apps",
        "title": "Terminal Pomodoro Timer",
        "description": "Beautiful TUI Pomodoro timer with work/break cycles, sound notifications, session logging, and stats.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["pomodoro.py", "sounds.py", "stats.py", "README.md"],
    },
    "markdown-note-app": {
        "category": "Mini Apps",
        "title": "Markdown Note-Taking App",
        "description": "Vim-like terminal note app — write in Markdown, search by tag, auto-save, and export to HTML.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["notes.py", "editor.py", "search.py", "README.md"],
    },
    "chat-room": {
        "category": "Mini Apps",
        "title": "WebSocket Chat Room",
        "description": "Real-time chat server with rooms, usernames, typing indicators, and message history using WebSockets.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["server.py", "client.html", "handlers.py", "README.md"],
    },

    # === WEB SCRAPING ===
    "hn-scraper": {
        "category": "Web Scraping",
        "title": "Hacker News Top Stories Scraper",
        "description": "Scrape HN front page, extract metadata, score trends over time, and export to CSV/JSON.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["hn_scraper.py", "analyzer.py", "README.md"],
    },
    "price-tracker": {
        "category": "Web Scraping",
        "title": "E-commerce Price Tracker",
        "description": "Track product prices across Amazon, notify on price drops via email, chart price history.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["tracker.py", "notify.py", "chart.py", "products.json", "README.md"],
    },
    "job-scraper": {
        "category": "Web Scraping",
        "title": "Job Listing Aggregator",
        "description": "Scrape job boards (LinkedIn, Indeed, Glassdoor), deduplicate, filter by keywords, export CSV.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["scraper.py", "filters.py", "dedup.py", "README.md"],
    },

    # === API WRAPPERS ===
    "github-api-wrapper": {
        "category": "API Wrappers",
        "title": "GitHub REST API Python Wrapper",
        "description": "Lightweight wrapper for GitHub API — repos, issues, PRs, stars, with pagination and rate-limit handling.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["github_client.py", "models.py", "examples.py", "README.md"],
    },
    "openai-playground": {
        "category": "API Wrappers",
        "title": "OpenAI API Playground CLI",
        "description": "Interactive CLI to experiment with GPT models — chat, streaming, function calling, token counting.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["openai_cli.py", "chat.py", "tokens.py", "README.md"],
    },

    # === DEVOPS ===
    "docker-healthcheck": {
        "category": "DevOps",
        "title": "Docker Container Health Monitor",
        "description": "Monitor running containers — health checks, resource usage alerts, auto-restart, Slack notifications.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["monitor.py", "checks.py", "alert.py", "docker-compose.yml", "README.md"],
    },
    "log-analyzer": {
        "category": "DevOps",
        "title": "Real-time Log Analyzer",
        "description": "Tail log files, detect patterns/errors in real-time, aggregate stats, and alert on anomalies.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["logwatch.py", "patterns.py", "dashboard.html", "README.md"],
    },
    "ci-cd-simulator": {
        "category": "DevOps",
        "title": "CI/CD Pipeline Simulator",
        "description": "Simulate a CI/CD pipeline locally — build, test, deploy stages with YAML config and parallel execution.",
        "language": "python",
        "difficulty": "advanced",
        "files": ["pipeline.py", "executor.py", "pipeline.yaml", "README.md"],
    },

    # === DATA SCIENCE ===
    "data-profiler": {
        "category": "Data Science",
        "title": "CSV Data Profiler",
        "description": "Auto-profile any CSV — column types, null stats, distributions, correlations, and generate HTML report.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["profiler.py", "report_template.html", "README.md"],
    },
    "stock-analyzer": {
        "category": "Data Science",
        "title": "Stock Market Technical Analyzer",
        "description": "Fetch stock data, compute MACD/RSI/Bollinger Bands, detect patterns, and plot interactive charts.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["stocks.py", "indicators.py", "charts.py", "README.md"],
    },
    "text-classifier": {
        "category": "Data Science",
        "title": "Text Classifier with TF-IDF + Naive Bayes",
        "description": "Train a text classifier from scratch — tokenization, TF-IDF vectorization, Naive Bayes, evaluation.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["classifier.py", "vectorizer.py", "train.csv", "README.md"],
    },

    # === GAMES ===
    "terminal-snake": {
        "category": "Games",
        "title": "Terminal Snake Game",
        "description": "Classic Snake in the terminal with keyboard controls, difficulty levels, high scores, and smooth rendering.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["snake.py", "engine.py", "highscores.json", "README.md"],
    },
    "text-adventure": {
        "category": "Games",
        "title": "Text Adventure Game Engine",
        "description": "Build your own text adventure — room descriptions, inventory system, NPCs, and a simple scripting language.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["adventure.py", "world.json", "parser.py", "README.md"],
    },
    "wordle-clone": {
        "category": "Games",
        "title": "Wordle Clone — Terminal Edition",
        "description": "Full Wordle clone with colored feedback, keyboard hints, word list from official dictionary, and daily challenge mode.",
        "language": "python",
        "difficulty": "beginner",
        "files": ["wordle.py", "words.txt", "colors.py", "README.md"],
    },

    # === NETWORKING ===
    "port-scanner": {
        "category": "Networking",
        "title": "Multi-threaded Port Scanner",
        "description": "Fast TCP port scanner with banner grabbing, service detection, and JSON/HTML report output.",
        "language": "python",
        "difficulty": "intermediate",
        "files": ["scanner.py", "banners.py", "reporter.py", "README.md"],
    },
    "packet-sniffer": {
        "category": "Networking",
        "title": "Network Packet Analyzer",
        "description": "Capture and decode TCP/UDP/ICMP packets, show real-time traffic stats, protocol distribution charts.",
        "language": "python",
        "difficulty": "advanced",
        "files": ["sniffer.py", "decoder.py", "stats.py", "README.md"],
    },
    "http-server": {
        "category": "Networking",
        "title": "HTTP Server from Scratch",
        "description": "Build a minimal HTTP/1.1 server using raw sockets — routing, static files, middleware, keep-alive.",
        "language": "python",
        "difficulty": "advanced",
        "files": ["server.py", "router.py", "middleware.py", "README.md"],
    },

    # === DATABASES ===
    "key-value-store": {
        "category": "Databases",
        "title": "Persistent Key-Value Store",
        "description": "Build a disk-backed KV store with Write-Ahead Log, SSTables, compaction, and range queries.",
        "language": "python",
        "difficulty": "advanced",
        "files": ["kvstore.py", "wal.py", "sstable.py", "README.md"],
    },
    "query-parser": {
        "category": "Databases",
        "title": "SQL Query Parser & Optimizer",
        "description": "Parse SQL SELECT statements into AST, apply basic optimizations (predicate pushdown, index selection).",
        "language": "python",
        "difficulty": "advanced",
        "files": ["lexer.py", "parser.py", "optimizer.py", "README.md"],
    },
}
